name: Validate exceptions.json

on:
  push:
    paths:
      - flatpak_builder_lint/staticfiles/exceptions.json
  pull_request:
    paths:
      - flatpak_builder_lint/staticfiles/exceptions.json

jobs:
  lint:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Validate exceptions.json
        run: python3 utils/validator.py
